Personal_diary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include("Personal_diarys.urls")),
]

Personal_diarys/urls.py
"""Определяет схемы URL для Personal_diarys"""
from django.urls import path
from . import views


app_name = 'Personal_diarys'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    
    path('topics/', views.topics, name='topics'),

    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),

    # Страница добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),

    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),

    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

    # Удаление темы
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),

    # Удаление записи
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),

    # Страница регистрации.
    path('register/', views.register, name='register'),
]

Personal_diarys/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    '''Тема, которую изучает пользователь'''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        '''Возвращает строковое представление модели'''
        return self.text

class Entry(models.Model):
    '''Информация, изученная пользователем по теме'''
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''Возвращает строковое представление модели'''
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

users/models.py
from django.db import models

# Create your models here.

Personal_diarys/forms.py
from django import forms
from .models import  Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

Personal_diarys/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


def check_topic_owner(topic, request):
    """Проверка того, что тема принадлежит текущему пользователю"""
    if topic.owner != request.user:
        raise Http404

def index(request):
    """ Домашняя страница приложения Personal_diary"""
    return render(request, 'Personal_diarys/index.html')

@login_required
def topics(request):
    """Выводит список тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'Personal_diarys/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все её записи"""
    topic = Topic.objects.get(id=topic_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    check_topic_owner(topic, request) 
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'Personal_diarys/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправленные данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('Personal_diarys:topics')

    # Вывести пустую или недействительную форму
    context = {'form': form}
    return render(request, 'Personal_diarys/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return redirect('Personal_diarys:topic', topic_id=topic_id)

    # Вывести пустую или недействительную форму
    context = {'topic': topic, 'form': form}
    return render(request, 'Personal_diarys/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    
    check_topic_owner(topic, request)

    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('Personal_diarys:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'Personal_diarys/edit_entry.html', context)

@login_required
def delete_topic(request, topic_id):
    """Удаляет тему"""
    topic = Topic.objects.get(id=topic_id)
    if request.method == 'POST':
        topic.delete()
        return redirect('Personal_diarys:topics')

    return render(request, 'Personal_diarys/delete_topic.html')

@login_required
def delete_entry(request, entry_id):
    """Удаляет запись"""
    entry = Entry.objects.get(id=entry_id)
    if request.method == 'POST':
        entry.delete()
        return redirect('Personal_diarys:topics')

    return render(request, 'Personal_diarys/delete_entry.html')

#Нужно чтобы при делет ентри переходило на тему а не на все темы

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('Personal_diarys:index')

    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

Personal_diarys/templates/Personal_diarys/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="ru">
  <head>
  <body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <a class="navbar-brand" href="{% url 'Personal_diarys:index' %}">
        ДНЕВНИК</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarCollapse" aria-controls="navbarCollapse"
          aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Personal_diarys:topics' %}">
              ТЕМЫ</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text">Приветствуем вас, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:logout' %}">ВЫХОД</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:register' %}">РЕГИСТРАЦИЯ</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:login' %}">ВХОД</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
        {% block content %}{% endblock content %}
    </main>

  </body>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
      shrink-to-fit=no">
    <title>ДНЕВНИК</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
  </head>
</html>

Personal_diarys/templates/Personal_diarys/delete_entry.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  <h3><a>Удаление записи</a></h3>
{% endblock page_header %}

{% block content %}
    
  <h3><a>Вы точно хотите эту запись?</a></h3>
  <form method='post'>
      {% csrf_token %}
      {{ form.as_p }} 
      <input class="btn btn-lg btn-danger" type="submit" value="Удалить">
      <a class="btn btn-lg btn-primary" href="{% url 'Personal_diarys:topics' %}">Отмена</a>
  </form>  
{% endblock content %}

<!-- Нужно чтобы после удаления переходило на тему назад, а не на все темы -->

Personal_diarys/templates/Personal_diarys/delete_topic.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  <h3><a>Удаление темы</a></h3>
{% endblock page_header %}

{% block content %}
    
  <h3><a>Вы точно хотите удалить тему? Все записи и сама тема будут стёрты! </a></h3>
  <form method='post'>
      {% csrf_token %}
      {{ form.as_p }} 
      <input class="btn btn-lg btn-danger" type="submit" value="Удалить">
      <a class="btn btn-lg btn-primary" href="{% url 'Personal_diarys:topics' %}">Отмена</a>
  </form>  
{% endblock content %}

Personal_diarys/templates/Personal_diarys/edit_entry.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  <h3><a>Редактирование записи</a></h3>
{% endblock page_header %}

{% block content %}
  <p><a class="btn btn-primary" href="{% url 'Personal_diarys:topic' topic.id %}">{{ topic }}</a></p>
  <div class=card-header>
      <p class="lead">Введите текст</p>
  </div>
  
  <form action="{% url 'Personal_diarys:edit_entry' entry.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-lg btn-primary" name="submit">Сохранить измменения</button>
  </form>

{% endblock content %}

Personal_diarys/templates/Personal_diarys/index.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  {% if user.is_authenticated %}
    <div class="jumbotron">
      <h1 class="display-3">Личный дневник</h1>
      <p class="lead">Запишите, что нового узнали в последнее время.</p>

      <a class="btn btn-lg btn-primary" href="{% url 'Personal_diarys:new_topic' %}"
          role="button">Добавить тему &raquo;</a>
    </div>
  {% else %}
    <div class="jumbotron">
      <h1 class="display-3">Личный дневник</h1>
      <p class="lead">Заведите свой собственный дневник и ведите список тем,
          которые наиболее интересны вам. Всякий раз, когда вы узнаёте что-то новое
          по какой-либо теме, делайте запись с кратким изложением того, что вы узнали.</p>

      <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
          role="button">Регистрация &raquo;</a>
      
      <a class="btn btn-lg btn-primary" href="{% url 'users:login' %}"
          role="button">Вход &raquo;</a>
    </div>  
  {% endif %}  
{% endblock page_header %} 

Personal_diarys/templates/Personal_diarys/new_entry.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  <h3><a>Расскажите, что нового узнали</a></h3>
{% endblock page_header %}

{% block content %}
  <p><a class="btn btn-primary" href="{% url 'Personal_diarys:topic' topic.id %}">{{ topic }}</a></p>

  <form action="{% url 'Personal_diarys:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-lg btn-primary" name="submit">Добавить запись</button>
  </form>

{% endblock content %}

Personal_diarys/templates/Personal_diarys/new_topic.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  <h3><a>Введите название темы:</a></h3>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'Personal_diarys:new_topic' %}" method='post'>
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-lg btn-primary" name="submit">Добавить</button>
  </form>

{% endblock content %}

Personal_diarys/templates/Personal_diarys/topic.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  <div class="jumbotron">
  <h1>{{ topic }}</h1>
  </div>
{% endblock page_header %}

{% block content %}
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true" aria-label="Previous" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span></a>
    </li>
    <li class="page-item"><a href="#" class="page-link">1</a></li>
    <li class="page-item">
      <a href="#" class="page-link" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
  </nav>
  <p>
    <a class="btn btn-primary" href="{% url 'Personal_diarys:new_entry' topic.id %}">Добавить новую запись</a>
  </p>   
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a class="btn btn-light" href="{% url 'Personal_diarys:edit_entry' entry.id %}">
            Редактировать</a></small>
        <small><a class= "btn btn-light" href="{% url 'Personal_diarys:delete_entry' entry.id %}">
          Удалить </a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
  {% empty %}
    <p>В этой теме нет записей.</p>
  {% endfor %}
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true" aria-label="Previous" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span></a>
    </li>
    <li class="page-item"><a href="#" class="page-link">1</a></li>
    <li class="page-item">
      <a href="#" class="page-link" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
  </nav>
{% endblock content %}

<!-- Доработать переключение страниц -->

    

Personal_diarys/templates/Personal_diarys/topics.html
{% extends "Personal_diarys/base.html" %}

{% block page_header %}
  <div class="jumbotron">
    <h1>Темы</h1>
  </div>
{% endblock page_header %}

{% block content %}
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true" aria-label="Previous" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span></a>
    </li>
    <li class="page-item"><a href="#" class="page-link">1</a></li>
    <li class="page-item">
      <a href="#" class="page-link" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
  </nav>
  <h3><a href="{% url 'Personal_diarys:new_topic' %}">Добавить новую тему</h3>
    {% for topic in topics %}
    <div class="list-group">
      <h3>
        <a href="{% url 'Personal_diarys:topic' topic.id %}" 
        class="list-group-item list-group-item-action list-group-item-info">{{ topic }}</a>
      </h3>
    </div>
    <h6>
      <a href="{% url 'Personal_diarys:delete_topic' topic.id %}"
      class= "btn btn-lg btn-light" >Удалить тему</a>
    </h6>
    {% empty %}
    <li><h3>Темы еще не добавлены.</h3></li>
    {% endfor %}
  <nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true" aria-label="Previous" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span></a>
    </li>
    <li class="page-item"><a href="#" class="page-link">1</a></li>
    <li class="page-item">
      <a href="#" class="page-link" aria-label="Next">
      <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
  </nav>
{% endblock content %}
 
<!-- Доработать переключение страниц -->